### ISSUE TITLE
Could not find a part of the path for DbImports.hbs

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#155]
I have the same issue while running 
`dotnet ef dbcontext scaffold "connectionstring" 
Microsoft.EntityFrameworkCore.SqlServer -o Models --schema dbo --context MyDataContext -f` for the first time
````
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\source\api\api.dbup\bin\Debug\net5.0\CodeTemplates\CSharpDbContext\Partials\DbImports.hbs'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at EntityFrameworkCore.Scaffolding.Handlebars.Internal.FileSystemFileService.RetrieveFileContents(String directoryName, String fileName)
   at EntityFrameworkCore.Scaffolding.Handlebars.FileSystemTemplateFileService.RetrieveTemplateFileContents(String relativeDirectory, String fileName, String altRelativeDirectory)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsDbContextTemplateService.GetPartialTemplates(LanguageOptions language)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsTemplateService.RegisterPartialTemplates()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
````

_Originally posted by @egorpavlikhin in https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/132#issuecomment-783802320_

**Comment by tonysneed** [comment]
@egorpavlikhin I'm not able to replicate this error. In a .NET 5.0 Class Library, I am using the following packages:
- Microsoft.EntityFrameworkCore.SqlServer 5.0.3
- Microsoft.EntityFrameworkCore.Design 5.0.3
- EntityFrameworkCore.Scaffolding.Handlebars 5.0.2

Are you using these same versions? Can you create a GitHub repo to replicate the error?

It looks like you may be using a project that was created with a prior version of the Handlebars scaffolding package which did not contain `DbImports.hbs`. You can copy the file from [here](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/src/EntityFrameworkCore.Scaffolding.Handlebars/CodeTemplates/CSharpDbContext/Partials/DbImports.hbs) to your `CodeTemplates\CSharpDbContext\Partials` folder.

**Comment by tonysneed** [comment]
Closing for now. Please re-open if needed.

**Comment by OronDF343** [comment]
Hi, I have encountered this issue in a fresh ASP.NET Core Empty project targeting .NET 5.0.
I am using the latest stable NuGet packages and tools.

 - EntityFrameworkCore.Scaffolding.Handlebars 5.0.2
 - Microsoft.EntityFrameworkCore 5.0.6
 - Microsoft.EntityFrameworkCore.Abstractions 5.0.6
 - Microsoft.EntityFrameworkCore.Analyzers 5.0.6
 - Microsoft.EntityFrameworkCore.Design 5.0.6
 - Microsoft.EntityFrameworkCore.Relational 5.0.6
 - Microsoft.EntityFrameworkCore.SqlServer 5.0.6

```dotnet ef dbcontext scaffold Name=ConnectionStrings:Training Microsoft.EntityFrameworkCore.SqlServer --use-database-names --output-dir Models --context-dir Services```
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Oronf\source\repos\TestEFCore\TestEFCore\bin\Debug\net5.0\CodeTemplates\CSharpDbContext\Partials\DbImports.hbs'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at EntityFrameworkCore.Scaffolding.Handlebars.Internal.FileSystemFileService.RetrieveFileContents(String directoryName, String fileName)
   at EntityFrameworkCore.Scaffolding.Handlebars.FileSystemTemplateFileService.RetrieveTemplateFileContents(String relativeDirectory, String fileName, String altRelativeDirectory)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsDbContextTemplateService.GetPartialTemplates(LanguageOptions language)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsTemplateService.RegisterPartialTemplates()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not find a part of the path 'C:\Users\Oronf\source\repos\TestEFCore\TestEFCore\bin\Debug\net5.0\CodeTemplates\CSharpDbContext\Partials\DbImports.hbs'.
```
