### ISSUE TITLE
Could not load file or assembly 'Handlebars, Version=1.9.4.0

### ISSUE THREAD

**Issue by jorgegarmilla** [TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars#25]
In step 5 I receive exception described below. I am using ASP Core 2.1....

System.IO.FileLoadException: Could not load file or assembly 'Handlebars, Version=1.9.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661'. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
File name: 'Handlebars, Version=1.9.4.0, Culture=neutral, PublicKeyToken=22225d0bf33cd661' ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsHelperService.RegisterHelpers()
   at EntityFrameworkCore.Scaffolding.Handlebars.HbsCSharpModelGenerator.GenerateModel(IModel model, String namespace, String contextDir, String contextName, String connectionString, ModelCodeGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by jorgegarmilla** [comment]
I installed nuget package "Handlerbars.Net" (v 1.9.4) but it still happens

**Comment by tonysneed** [comment]
Are you getting this error with the latest version?

**Comment by tonysneed** [comment]
This should be fixed in the current version. Otherwise, please re-open.

**Comment by jorgegarmilla** [comment]
Thanks Tony. It worked as expected... reading what has been generated. Looks really good ;-)
